name: Workflow-DevOps

on:
  push:
    branches:
      - release/*
      - feature/*

  schedule:
    - cron: '45 19 * * 1'
    - cron: '00 0 * * 2'

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v2

      - name: Running tests
        run: |
          echo "Ejecutando pruebas"

  build:
    runs-on: windows-latest
    needs: test
    steps:
      - name: Checking out code
        uses: actions/checkout@v2

      - name: Building the project
        run: |
          echo "Compilando el proyecto"

  deploy:
    runs-on: windows-latest
    needs: build
    if: startsWith(github.ref, 'refs/heads/release/') || startsWith(github.ref, 'refs/heads/feature/')
    steps:
      - name: Checking out code
        uses: actions/checkout@v2

      - name: Deploying the project
        run: |
          echo "Deployando"